[package]
name = "riga-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
riga-kernel = { path = "../../../crates/riga-kernel" }
tauri = { version = "2.0", default-features = false, features = ["wry"] }

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[lints]
workspace = true
